"""empty message

Revision ID: 3ccba0f0151c
Revises: e9bb0329d3b8
Create Date: 2023-12-25 12:34:56.918442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ccba0f0151c'
down_revision = 'e9bb0329d3b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_ban',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(length=48), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('t_id', sa.String(length=48), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('word_h_reply',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(length=48), nullable=True),
    sa.Column('reply_text', mysql.LONGTEXT(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('t_id', sa.String(length=48), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('word_reply',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(length=48), nullable=True),
    sa.Column('reply_text', mysql.LONGTEXT(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('t_id', sa.String(length=48), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_reply')
    op.drop_table('word_h_reply')
    op.drop_table('word_ban')
    # ### end Alembic commands ###
