"""empty message

Revision ID: c81c4e78c19f
Revises: 3ccba0f0151c
Create Date: 2023-12-25 16:46:06.988106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c81c4e78c19f'
down_revision = '3ccba0f0151c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keywords',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('word', sa.String(length=48), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('t_id', sa.String(length=48), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keywords')
    # ### end Alembic commands ###
