"""empty message

Revision ID: cd126026ae53
Revises: 
Create Date: 2023-12-22 02:08:09.589681

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd126026ae53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conf',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('value', mysql.LONGTEXT(), nullable=True),
    sa.Column('typestr', sa.String(length=48), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('memo', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('money', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('typestr', sa.String(length=256), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('t_id', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('recharge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('money', sa.String(length=256), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('from_address', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('t_id', sa.String(length=96), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('firstname', sa.String(length=96), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('balance', sa.String(length=128), nullable=True),
    sa.Column('register_time', sa.DateTime(), nullable=True),
    sa.Column('t_id', sa.String(length=96), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('wallet',
    sa.Column('id', sa.String(length=68), nullable=False),
    sa.Column('money', sa.String(length=256), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('sender', sa.String(length=256), nullable=True),
    sa.Column('recipient', sa.String(length=256), nullable=True),
    sa.Column('typestr', sa.String(length=48), nullable=True),
    sa.Column('insert_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet')
    op.drop_table('user')
    op.drop_table('recharge')
    op.drop_table('orders')
    op.drop_table('conf')
    # ### end Alembic commands ###
